title: ALTERXX
description: ALTERXX's Personal Website (Maybe)
baseurl: ""

theme: minima

username: alterxx
typing_text: what

email: iam.alterxx@gmail.com
telegram_username: alterxx
github_username: alterxx

show_aboutme_card: false
about_me_title: About Me
about_me_description: <empty>

show_skills_card: true
skills_title: Skills

show_timeline_card: true
timeline_title: Education & Experience
#cv_download_link: https://resume.io/r/L57OtJ63W

show_projects_card: true
show_projects: true
projects_title: Work Projects
show_os_projects: false
os_projects_title: Portfolio Projects

show_contact_card: true
contact_title: Contacts
contact_description: Feel free to contact me wherever is comfortable for you

repository: alterxx/alterxx.github.io
  
projects:
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
      - alterxx

plugins:
  - "jekyll-github-metadata"
