title: David Kobalia
description: David Kobalia's Personal Website
baseurl: ""

username: David Kobalia
typing_text: Software Engineer / QA Tester

email: daweedkob@gmail.com
telegram_username: in_solitum
linkedin_username: dkobalia
github_username: insolitum
